#!/usr/bin/env bash
###############################################################################
#
# Usage: juff [options]
#
# Options:
# -i | --inbox <directory>
# -d | --daemon
# -s | --sync
# <recipient> | -b | --broadcast [<text> | <Windows or Unix filepath>]
# -v | --version
# -h | --help
# -q | --quiet
#
# Copyright (C) 2021 Somajit Dey <dey.somajit@gmail.com>
# License: GPL-3.0-or-later
#
###############################################################################
#
# Customizable constants
readonly Default_inbox="${HOME}/Inbox_JuFF"
readonly GPG_program="gpg"
readonly Debug_mode="on"
readonly Version="beta"

###############################################################################

abs_path(){
# Transforms any path, including windows paths, to absolute path. Expands ~ too
# Exitcode: 0 (output to stdout) if path exists, 1 (outout to stderr) otherwise
  local path="${1}"
# Windows to Unix path [if operand is Unix path then wslpath outputs to stderr]
  local buffer=$(wslpath -u "${path}" 2>/dev/null); path="${buffer:-"${path}"}"
  path="${path//\\/}"  # Remove backslash, if any
  path="${path//\~/"${HOME}"}"  # Tilde expansion: ~
  path="${path//\~-/"${OLDPWD}"}"  # Tilde expansion: ~-
  [[ "${path}" != /* ]] && path="${PWD}/${path}"
  [[ -e "${path}" ]] && echo "${path}" && return 0
  echo "${path}" >&2 && return 1 
}

readonly This_code="$(abs_path "${BASH_SOURCE}")"
readonly This_prog="${0}"
readonly This_pid="${$}"
readonly Red="$(tput setaf 1)"
readonly Green="$(tput setaf 2)"
readonly Yellow="$(tput setaf 3)"
readonly Blue="$(tput setaf 4)"
readonly Magenta="$(tput setaf 5)"
readonly Cyan="$(tput setaf 6)"
readonly Normal="$(tput sgr0)"
readonly Bold="$(tput bold)"
readonly Underline="$(tput smul)"
readonly Bell="$(tput bel)"
readonly Prefix_gpg="${GPG_program} --batch --no-tty --quiet --no-greeting"

error_exit(){
  local error_msg="${1:-"Unknown error"}"
  printf "%s\n" "${error_msg}"
  exit 1
} >&2

showhelp(){
  cat <<"_EOF_"

JuFF is a secure chatting and file-sharing application run from a single script

Usage: juff [options]

With no options, JuFF is interactive

Options:
  -i | --inbox <directory>
     Specify your JuFF inbox if it is anything other than the default
  -s | --sync
     Sync once. Ignores other options except -q or --quiet and -i or --inbox
  -d | --daemon
     Sync in background. Implies --quiet. Ignores other options except --inbox 
  <recipient> | -b | --broadcast [<text> | <Windows or Unix filepath>]
     Specify the recipient account. If ambiguous, JuFF becomes interactive
     -b or --broadcast implies everyone in JuFF is a recipient
     Follow recipient name with message or path or name of the file to be sent
     If no text or filename follows recipient name, JuFF becomes interactive
  -v | --version
  -h | --help
  -q | --quiet
     Be as quiet as possible. Limits interaction with user

Ex: juff email@domain "Welcome to JuFF"
Ex: juff --quiet alias#email@domain "$(cat my_words.txt)" # Send text from file
Ex: juff email@domain "~/share.me" # File-sharing
Ex: juff daemon # You may include this in your .bashrc file
Ex: juff sync

_EOF_
  
}

parse_cmdline(){
  while [[ -n "${1}" ]]; do
    case "${1}" in
      -i | --inbox)
        shift
        Inbox="${1}"
        ;;
      -q | --quiet)
        Quiet_mode="on"
        ;;
      -v | --version)
        printf "%s\n" "${Version}" ; exit
        ;;
      -h | --help)
        showhelp ; exit
        ;;
      -d | --daemon)
        Daemon_mode="on" ; break
        ;;
      -s | --sync)
        Sync_mode="on" ; break
        ;;
      -b | --broadcast)
        Broadcast_mode="on" ; msg_or_file="${2}"; break
        ;;
      -* | --*)
        printf "%s\n" "Option not recognized. See help: ${This_prog} -h" >&2
        exit 1
        ;;
      *)
        correspondent="${1}" ; msg_or_file="${2}" ; break
        ;;
    esac
    shift
  done

  readonly Inbox="${Inbox:="${Default_inbox}"}"
  readonly Quiet_mode="${Quiet_mode:="off"}"
  readonly Sync_mode="${Sync_mode:="off"}"
  readonly Daemon_mode="${Daemon_mode:="off"}"
  readonly Broadcast_mode="${Broadcast_mode:="off"}"
}

parse_cmdline "${@}" && echo ${correspondent} && echo ${msg_or_file} && echo ${Inbox}
